[metadata]
name = samplersLib
version = 2601.0
description = "A samplers library for (in)active sampling that supports both supports both {{online and offline interactions}} with processes executed by external libraries"
author = Ahmed H. Bayoumy
author_email = ahmed.bayoumy@mail.mcgill.ca
long_description = file: README.md
long_description_content_type = text/markdown
license_file = LICENSE
url = https://github.com/Ahmed-Bayoumy/samplersLib
project_urls =
    Bug Tracker = https://github.com/Ahmed-Bayoumy/samplersLib/issues
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    License :: OSI Approved :: BSD 3-Clause License
    Operating System :: OS Independent
    Intended Audience :: Developers

[options]
python_requires = >=3.10
package_dir =
    =src
packages = find:

[options.packages.find]
where = src

[options.extras_require]
testing =
    pytest>=9.0.2
    pytest-cov>=7.0.0
    mypy>=1.19.1
    flake8>=7.3.0
    tox>=4.32.0

[options.package_data]
samplersLib = py.typed

[flake8]
max-line-length = 160